Minimale_sans_Plateau_Global.c
void reinitialiser_perso(t_character plateau[10][10])
References t_character::money.
Referenced by main.
void reinitialiser_perso2(t_character *plateau[10][10])
References t_character::money, t_richesses::argent, t_argent::or.
Referenced by main.
void afficher_perso(t_character perso)
References t_character::money, t_richesses::argent, t_argent::or, t_argent::argent, t_richesses::joyaux, t_character::age.
Referenced by main.
int main()
References t_character::money, t_character::age, reinitialiser_perso, reinitialiser_perso2, afficher_perso.