Minimale.c
KNRM
Referenced by main.
KRED
Referenced by main.
KGRN
KYEL
KBLU
Referenced by main.
KMAG
Referenced by main.
KCYN
KWHT
int compteur_tour
Referenced by main.
int compteur_joueurs_vivants
Referenced by all_dead_but_one.
t_character Valid_chars_IA[MaxTab][MaxTab]
char particule_generateur_nom[][20][][20]
Referenced by creer_terrain_rapide, generation_nom_personnage.
t_character Plateau[TAILLE_MATRICE][TAILLE_MATRICE][TAILLE_MATRICE][TAILLE_MATRICE]
t_coord depValid[TAILLE_MATRICE *TAILLE_MATRICE][3][TAILLE_MATRICE *TAILLE_MATRICE][3]
t_player player[MaxTab][MaxTab]
int indiceTabDepValid
int life_check(int joueur_courant)
Fonction qui vérifie si un joueur a encore des personnages vivants sur le terrain. Appelle are_my_mates_alive(int joueur_courant) pour déterminer le joueur est encore en jeu. Renvoie 1 si le joueur a encore des personnages en vie, sinon 0.
References are_my_mates_alive, t_player::alive.
Referenced by tour.
void joueur_liste_suivant(int nb_joueur, int *joueur_courant)
Prend en paramètre le nombre de joueurs et incrémente le numéro de joueur de façon à ne pas dépasser le nombre de joueurs.
Referenced by main.
void creer_terrain_rapide(t_camp camp, int x, int y)
Création brève de terrain ou obstacle, possible implémentation de génération aléatoire en cas d'obstacle.
References MaxString, obstacle, case_obstacle, particule_generateur_nom, generation_nombre_aleatoire, terrain, case_terrain, t_character::camp, t_character::position, t_coord::X, t_coord::Y.
Referenced by init_plateau, main.
void vider_buffer(void)
int are_my_mates_alive(int joueur_courant)
Prend en paramètre le joueur courant et vérifie si tous ses personnages ne sont pas morts.
References TAILLE_MATRICE, TRAP_UNIT.
Referenced by life_check.
int calcul_persos_IA(int joueur_courant)
Calcule le nombre de personnage controlé par l'IA.
References init_char_table, TAILLE_MATRICE.
Referenced by tour_IA.
void afficher_plateau_orientation(int joueur_courant)
Affiche le plateau avec les caractères correspondants à l'orientation.
References TAILLE_MATRICE, TRAP_UNIT, up, left, right, down.
Referenced by Charger, choix_deplacement_humain, choix_cible_humain, selection_perso, orienter_perso_fleches, tour, main.
void generation_nom_personnage(char *nom)
génère aléatoirement un nom pour un perso
References generation_nombre_aleatoire, particule_generateur_nom.
Referenced by creer_perso_rapide.
void players_life_check()
Actualise le fait que les joueurs soient vivants ou non.
References MaxTab, t_player::alive, TAILLE_MATRICE, TRAP_UNIT, t_character::camp.
Referenced by main.
void Sauvegarder(int joueur_courant)
Sauvegarde la partie en cours dans un fichier.
References TAILLE_MATRICE.
Referenced by tour.
int Charger(int joueur_courant)
Permet de charger une partie depuis un fichier de sauvegarde.
References TAILLE_MATRICE, afficher_plateau_orientation.
Referenced by tour.
int generation_nombre_aleatoire(int max)
Fonction qui renvoi un nombre aléatoire entre 0 et 'max'.
Referenced by choix_deplacement_IA, choix_cible_IA, creer_terrain_rapide, generation_nom_personnage, spawn_sauvage, spawn_character, main.
void deplacer_perso(t_coord case_perso, t_character *selected_character)
Déplace le personnage sur le terrain Remplace la case où se trouvait le perso par une case terrain, et place le perso sur la 'case_perso'. Si la 'case_perso' contenait un piège, le perso perd des HP.
References t_character::position, t_coord::X, t_coord::Y, case_terrain, t_character::type, TRAP_UNIT, t_character::status, t_status::HP, t_character::stats, t_stats::ATK.
Referenced by choix_deplacement_humain, tour, tour_IA.
int cases_voisines_calcul(t_coord coordonnees)
Renvoi le nombre de case voisine vide; met dans la file, la liste des coordonnées voisines accessibles.
References t_coord::X, t_coord::Y, t_character::camp, t_character::type, TRAP_UNIT, TAILLE_MATRICE, file_ajouter.
Referenced by deplacements_valides.
void deplacements_valides(int *nbDepValid, t_character *selected_character)
Calcule les positions de déplacement valide, les met dans la liste.
References liste_init, file_init, t_character::position, file_ajouter, liste_ajout_droit, file_retirer, cases_voisines_calcul, liste_suppr_doublon, liste_calculer_nombre_elements.
Referenced by tour, tour_IA.
t_coord choix_deplacement_humain(int joueur_courant, int *nbDepValid, t_character *selected_character)
Permet au joueur de choisir la destination Le joueur déplace un curseur qui représente son joueur courant, il est limité aux limites du plateau et au nombre de déplacements qu'il possède.
References t_character::position, t_coord::X, t_coord::Y, pile_init, pile_empiler, pile_sommet, t_character::type, TRAP_UNIT, TAILLE_MATRICE, deplacer_perso, t_character::stats, t_stats::MVT, afficher_plateau_orientation, curseur, pile_depiler, terrain.
Referenced by tour.
t_coord choix_deplacement_IA(int *nbDepValid, t_character *selected_character)
cette fonction retourne les coordonnées du déplacement choisi pour l'IA
References liste_en_tete, liste_est_hors_liste, liste_valeur_elt, liste_suivant, generation_nombre_aleatoire, t_coord::X, t_coord::Y, t_character::name.
Referenced by tour_IA.
void init_plateau()
Initialise le plateau en le remplissant de terrain par défaut.
References TAILLE_MATRICE, creer_terrain_rapide, terrain.
int cases_voisines_ATK(t_coord coordonnees)
Renvoi le nombre de case voisine. Met dans la file la liste des coordonnées voisines.
References t_coord::X, TAILLE_MATRICE, file_ajouter, t_coord::Y.
Referenced by viser_case_valide.
void viser_case_valide(t_skill skill, int *nbAtkValid, t_character *selected_character)
Calcule les positions d'attaques valides, les met dans la liste. une case vide peut être attaquée.
References liste_init, file_init, t_character::position, file_ajouter, liste_ajout_droit, t_skill::range, file_retirer, t_skill::type, TRAP, t_coord::X, t_coord::Y, t_character::camp, terrain, cases_voisines_ATK, liste_suppr_doublon, liste_calculer_nombre_elements.
Referenced by tour, tour_IA.
t_coord choix_cible_IA(t_skill skill, int *nbAtkValid)
Choisi parmi la liste des cases à attaquer pour l'IA, une case vide peut être attaquée.
References liste_en_tete, generation_nombre_aleatoire, liste_suivant, liste_valeur_elt, t_coord::X, t_coord::Y.
Referenced by tour_IA.
void init_char_table(t_character chars[])
Fonction d'initialisation d'un tableau de personnages. Remplit le tableau de personnages entré en paramètre de cases de terrain.
References MaxTab, character_default.
Referenced by calcul_persos_IA.
void afficher_skill(int skill_nb, t_skill skill, t_character selected_character)
Affiche le nom, la portée, la puissance d'une compétence.
References t_skill::name, t_skill::range, t_skill::type, EMPTY, ATK, t_character::stats, t_stats::ATK, t_skill::damage_coeff, MATK, t_stats::MATK.
Referenced by afficher_skill_list, select_skill.
void afficher_skill_list(t_character perso)
Affiche la liste des compétence d'un personnage.
References afficher_skill, t_character::skill, t_skill_list::a, t_skill_list::b, t_skill_list::c, t_skill_list::d, t_skill_list::e, t_skill_list::wait.
Referenced by afficher_infos_persos.
void afficher_infos_persos(t_character perso)
Affiche les informations du personnage.
References TAILLE_MATRICE, t_character::name, t_character::classe, t_character::status, t_status::HP, t_status::Max_HP, t_status::MP, t_status::Max_MP, t_character::stats, t_stats::ATK, t_stats::MATK, t_stats::DEF, t_stats::MDEF, t_stats::MVT, t_character::nb_action_tour, afficher_skill_list.
Referenced by choix_cible_humain, selection_perso.
t_coord choix_cible_humain(t_skill skill, int joueur_courant, t_character *selected_character)
Permet au joueur de choisir, grâce à un curseur, une case à attaquer.
References t_character::position, t_coord::X, t_coord::Y, afficher_plateau_orientation, TRAP_UNIT, afficher_infos_persos, curseur, TAILLE_MATRICE, liste_element_est_present.
Referenced by tour.
void selection_perso(int joueur_courant, t_character *selected_character)
Cette fonction permet au joueur de choisir un de ses persos sur le plateau grâce à un curseur.
References afficher_plateau_orientation, TRAP_UNIT, afficher_infos_persos, curseur, TAILLE_MATRICE, case_terrain.
Referenced by tour.
void passer_tour()
Fonction qui passe le tour du joueur actif.
Referenced by tour.
void suicide(int joueur_courant)
Fonction permetant au joueur courant d'abandonner la partie.
References TAILLE_MATRICE, case_terrain.
Referenced by tour.
t_skill select_skill(t_character selected_character)
Permet au joueur de choisir, graphiquement, une compétence à effectuer dans un menu.
References afficher_skill, t_character::skill, t_skill_list::a, t_skill_list::b, t_skill_list::c, t_skill_list::d, t_skill_list::e, t_skill_list::wait, skill_empty.
Referenced by tour.
t_targetOrientation get_target_orientation(t_character perso, t_coord cible)
Fonction déterminant quelle est l'orientation de la cible par rapport au joueur.
References t_character::position, t_coord::X, t_coord::Y, t_character::orientation, up, back, right, front, side, down, left.
Referenced by appliquer_action.
void appliquer_action(t_character lanceur, t_coord cible, t_skill action)
Fonction appliquant le skill du personnage lanceur à la case cible. Remplit le tableau de personnages entré en paramètre de cases de terrain.
References get_target_orientation, t_skill::type, MATK, t_coord::X, t_coord::Y, t_skill::damage_coeff, t_character::stats, t_stats::MATK, t_stats::MDEF, t_character::status, t_status::HP, ATK, t_stats::ATK, t_stats::DEF, EMPTY, TRAP, default_trap, t_character::type, TRAP_UNIT, t_character::camp, t_character::position, t_status::Max_HP, case_terrain.
Referenced by tour, tour_IA.
void orienter_perso_fleches(int joueur_courant, t_character *selected_character)
Cette fonction permet au joueur d'orienter son personnage avec les flèches directionnelles.
References t_character::orientation, afficher_plateau_orientation, t_character::position, t_coord::Y, t_coord::X, up, right, down, left.
Referenced by tour.
void character_hp_list()
affiche une liste avec les persos et leurs points de vie.
References TAILLE_MATRICE, t_character::position, t_coord::Y, t_character::name, t_character::status, t_status::HP, t_status::Max_HP.
Referenced by main.
void tour(int joueur_courant, int *nbAtkValid, int *nbDepValid, t_character *selected_character)
Fonction de déroulement d'un tour pour le joueur entré en paramètre.
References afficher_plateau_orientation, TAILLE_MATRICE, selection_perso, passer_tour, suicide, life_check, Sauvegarder, Charger, deplacements_valides, choix_deplacement_humain, deplacer_perso, t_coord::X, t_coord::Y, t_character::status, t_status::HP, t_status::Max_HP, case_terrain, select_skill, t_skill::type, EMPTY, viser_case_valide, appliquer_action, choix_cible_humain, t_character::position, orienter_perso_fleches.
Referenced by main.
int all_dead_but_one(int nb_joueurs)
Fonction déterminant si un seul joueur est vivant. Appellé par la fonction principale pour déterminer si c'est la fin de la partie. Renvoie 0 si plus d'un joueur survit, sinon renvoie 1.
References compteur_joueurs_vivants.
Referenced by main.
void creer_perso_rapide(t_camp camp, int x, int y, t_classe classe)
Création brève de perso.
References MaxString, generation_nom_personnage, character_default, character_berseker, character_mage, character_tank, character_soigneur, terrain, t_character::camp, t_character::position, t_coord::X, t_coord::Y, t_character::orientation, down, up, t_character::classe.
Referenced by spawn_sauvage, spawn_character, main.
void edit_stats(t_character perso, int HP, int Max_HP, int MP, int Max_MP, int ATK, int MATK, int DEF, int MDEF, int MVT)
modifie les statistiques d'un personnage
References t_character::position, t_coord::X, t_coord::Y, t_character::status, t_status::HP, t_status::Max_HP, t_status::MP, t_status::Max_MP, t_character::stats, t_stats::ATK, ATK, t_stats::MATK, MATK, t_stats::DEF, t_stats::MDEF, t_stats::MVT.
void spawn_sauvage()
Créé un personnage du camp neutre à une position aléatoire sur le terrain.
References t_player::alive, generation_nombre_aleatoire, TAILLE_MATRICE, creer_perso_rapide, sauvage, berseker, t_character::status, t_status::HP, t_status::Max_HP.
Referenced by main.
void spawn_character(t_camp camp_nouveau_perso)
Permet la création d'un personnage joueur à la position entrée.
References t_player::alive, generation_nombre_aleatoire, TAILLE_MATRICE, creer_perso_rapide.
void tour_IA(int joueur_courant, int *nbAtkValid, int *nbDepValid, t_character *selected_character)
Fonction de déroulement d'un tour pour l'IA.
References calcul_persos_IA, t_character::position, t_coord::X, t_coord::Y, t_character::camp, t_character::nb_action_tour, deplacements_valides, deplacer_perso, choix_deplacement_IA, t_character::skill, t_skill_list::a, t_skill::type, EMPTY, viser_case_valide, appliquer_action, choix_cible_IA.
Referenced by main.
void saisie_nombre_joueurs(int *nb_joueurs)
permet à l'utilisateur de rentrer le nombre de joueur à jouer
Referenced by main.
int main()
Fonction principale Fonction principale qui permet de jouer en mode Kill'em'all.
References saisie_nombre_joueurs, creer_terrain_rapide, obstacle, creer_perso_rapide, berseker, mage, soigneur, tank, default_class, players_life_check, MaxTab, KRED, KBLU, KMAG, KNRM, all_dead_but_one, compteur_tour, generation_nombre_aleatoire, spawn_sauvage, afficher_plateau_orientation, character_hp_list, sauvage, tour_IA, tour, joueur_liste_suivant.