file.c
TMAX
Referenced by file_ajouter, file_retirer, file_afficher_elt.
t_coord file[TMAX][TMAX]
int tete
int queueFile
int nbVal
void file_init()
Referenced by deplacements_valides, viser_case_valide.
void file_ajouter(t_coord a)
References TMAX.
Referenced by cases_voisines_calcul, deplacements_valides, cases_voisines_ATK, viser_case_valide.
void file_retirer(t_coord *val)
References TMAX.
Referenced by deplacements_valides, viser_case_valide.
int file_vide()
void file_liste_afficher_queue()
void file_afficher_elt(t_coord val)
References TMAX, t_coord::X, t_coord::Y.