liste.c
N_LISTE
t_coord T[N_LISTE][N_LISTE]
int queue
Referenced by liste_init, liste_est_vide, liste_est_hors_liste, liste_en_queue, liste_oter_elt, liste_ajout_droit, liste_ajout_gauche, liste_suppr_doublon.
int ec
Referenced by liste_init, liste_en_tete, liste_en_queue, liste_precedent, liste_suivant, liste_valeur_elt, liste_modif_elt, liste_oter_elt, liste_ajout_droit, liste_ajout_gauche.
void liste_init(void)
References queue, ec.
Referenced by deplacements_valides, viser_case_valide.
int liste_est_vide(void)
References queue.
Referenced by liste_en_tete, liste_en_queue, liste_ajout_droit, liste_ajout_gauche, liste_calculer_nombre_elements.
int liste_est_hors_liste(void)
References queue.
Referenced by liste_precedent, liste_suivant, liste_valeur_elt, liste_modif_elt, liste_oter_elt, liste_ajout_droit, liste_ajout_gauche, liste_afficher_contenu, liste_suppr_doublon, liste_calculer_nombre_elements, liste_element_est_present, choix_deplacement_IA.
void liste_en_tete(void)
References liste_est_vide, ec.
Referenced by liste_afficher_contenu, liste_afficher_queue, liste_suppr_doublon, liste_calculer_nombre_elements, liste_element_est_present, choix_deplacement_IA, choix_cible_IA.
void liste_en_queue(void)
References liste_est_vide, ec, queue.
void liste_precedent(void)
References liste_est_hors_liste, ec.
void liste_suivant(void)
References liste_est_hors_liste, ec.
Referenced by liste_afficher_contenu, liste_suppr_doublon, liste_calculer_nombre_elements, liste_element_est_present, choix_deplacement_IA, choix_cible_IA.
void liste_valeur_elt(t_coord *e)
References liste_est_hors_liste, ec.
Referenced by liste_afficher_contenu, liste_afficher_queue, liste_suppr_doublon, liste_element_est_present, choix_deplacement_IA, choix_cible_IA.
void liste_modif_elt(t_coord v)
References liste_est_hors_liste, ec.
void liste_oter_elt(void)
References liste_est_hors_liste, ec, queue.
Referenced by liste_suppr_doublon.
void liste_ajout_droit(t_coord e)
References liste_est_vide, ec, queue, liste_est_hors_liste.
Referenced by deplacements_valides, viser_case_valide.
void liste_ajout_gauche(t_coord e)
References liste_est_vide, ec, liste_est_hors_liste, queue.
void liste_afficher_contenu()
References liste_en_tete, liste_est_hors_liste, liste_valeur_elt, t_coord::X, t_coord::Y, liste_suivant.
void liste_afficher_queue()
References liste_en_tete, liste_valeur_elt, t_coord::X, t_coord::Y.
void liste_suppr_doublon()
References queue, liste_en_tete, liste_suivant, liste_valeur_elt, liste_est_hors_liste, t_coord::X, t_coord::Y, liste_oter_elt.
Referenced by deplacements_valides, viser_case_valide.
int liste_calculer_nombre_elements()
References liste_est_vide, liste_en_tete, liste_est_hors_liste, liste_suivant.
Referenced by deplacements_valides, viser_case_valide.
int liste_element_est_present(t_coord e, int numPile)
References liste_en_tete, liste_valeur_elt, liste_est_hors_liste, t_coord::X, t_coord::Y, liste_suivant.
Referenced by choix_cible_humain.