pile.c
M
Referenced by pile_empiler.
t_coord pile[M][M][M][M]
int sommet[M][M]
void pile_init(int numPile)
Referenced by choix_deplacement_humain.
void pile_empiler(t_coord coord, int numPile)
References M, t_coord::X, t_coord::Y.
Referenced by choix_deplacement_humain.
void pile_depiler(t_coord *coord, int numPile)
References t_coord::X, t_coord::Y.
Referenced by choix_deplacement_humain.
int pile_sommet(t_coord *coord, int numPile)
References t_coord::X, t_coord::Y.
Referenced by choix_deplacement_humain.
int pilevide(int numPile)