.TH "file.h" 3 "Tue Jan 6 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfile_init\fP ()"
.br
.ti -1c
.RI "void \fBfile_ajouter\fP (\fBt_coord\fP a)"
.br
.ti -1c
.RI "void \fBfile_retirer\fP (\fBt_coord\fP *val)"
.br
.ti -1c
.RI "int \fBfile_vide\fP ()"
.br
.ti -1c
.RI "void \fBfile_liste_afficher_queue\fP ()"
.br
.ti -1c
.RI "void \fBfile_afficher_elt\fP (\fBt_coord\fP val)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void file_afficher_elt (\fBt_coord\fPval)"

.PP
Definition at line 53 of file file\&.c\&.
.SS "void file_ajouter (\fBt_coord\fPa)"

.PP
Definition at line 16 of file file\&.c\&.
.SS "void file_init ()"

.PP
Definition at line 8 of file file\&.c\&.
.SS "void file_liste_afficher_queue ()"

.PP
Definition at line 47 of file file\&.c\&.
.SS "void file_retirer (\fBt_coord\fP *val)"

.PP
Definition at line 29 of file file\&.c\&.
.SS "int file_vide ()"

.PP
Definition at line 42 of file file\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Le jeu 4 from the source code\&.
