.TH "file.c" 3 "Mardi Janvier 6 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'file\&.h'\fP
.br
\fC#include 'header\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTMAX\fP   100"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBfile_init\fP ()"
.br
.ti -1c
.RI "void \fBfile_ajouter\fP (\fBt_coord\fP a)"
.br
.ti -1c
.RI "void \fBfile_retirer\fP (\fBt_coord\fP *val)"
.br
.ti -1c
.RI "int \fBfile_vide\fP ()"
.br
.ti -1c
.RI "void \fBfile_liste_afficher_queue\fP ()"
.br
.ti -1c
.RI "void \fBfile_afficher_elt\fP (\fBt_coord\fP val)"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define TMAX   100"

.PP
Définition à la ligne 4 du fichier file\&.c\&.
.SH "Documentation des fonctions"
.PP 
.SS "void file_afficher_elt (\fBt_coord\fPval)"

.PP
Définition à la ligne 53 du fichier file\&.c\&.
.SS "void file_ajouter (\fBt_coord\fPa)"

.PP
Définition à la ligne 16 du fichier file\&.c\&.
.SS "void file_init ()"

.PP
Définition à la ligne 8 du fichier file\&.c\&.
.SS "void file_liste_afficher_queue ()"

.PP
Définition à la ligne 47 du fichier file\&.c\&.
.SS "void file_retirer (\fBt_coord\fP *val)"

.PP
Définition à la ligne 29 du fichier file\&.c\&.
.SS "int file_vide ()"

.PP
Définition à la ligne 42 du fichier file\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Le jeu 4 à partir du code source\&.
