.TH "md__readme" 3 "Vendredi 16 Janvier 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__readme \- Readme 
Peut-être penser à la génération de terrain\&. Ca serait pas mal un ptit donjon avec des salles\&.
.PP
Configuration de Geany, cliquer sur le menu déroulant à côté de build, puis 'définir les commandes de construction' puis :
.PP
http://image.noelshack.com/fichiers/2014/51/1418816409-capture-du-2014-12-17-12-38-56.png 
