.TH "Minimale_sans_Plateau_Global.c" 3 "Mercredi Janvier 7 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Minimale_sans_Plateau_Global.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <ncurses\&.h>\fP
.br

.SS "Structures de données"

.in +1c
.ti -1c
.RI "struct \fBt_argent\fP"
.br
.ti -1c
.RI "struct \fBt_richesses\fP"
.br
.ti -1c
.RI "struct \fBt_character\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBreinitialiser_perso\fP (\fBt_character\fP plateau[10][10])"
.br
.ti -1c
.RI "void \fBreinitialiser_perso2\fP (\fBt_character\fP *plateau[10][10])"
.br
.ti -1c
.RI "void \fBafficher_perso\fP (\fBt_character\fP perso)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void afficher_perso (\fBt_character\fPperso)"

.PP
Définition à la ligne 30 du fichier Minimale_sans_Plateau_Global\&.c\&.
.SS "int main ()"

.PP
Définition à la ligne 35 du fichier Minimale_sans_Plateau_Global\&.c\&.
.SS "void reinitialiser_perso (\fBt_character\fPplateau[10][10])"

.PP
Définition à la ligne 16 du fichier Minimale_sans_Plateau_Global\&.c\&.
.SS "void reinitialiser_perso2 (\fBt_character\fP *plateau[10][10])"

.PP
Définition à la ligne 23 du fichier Minimale_sans_Plateau_Global\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Le jeu 4 à partir du code source\&.
