.TH "pile.c" 3 "Jeudi Janvier 15 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pile.c \- 
.PP
Projet informatique S3 Deplacement du personnage et colisions sur le parois\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'pile\&.h'\fP
.br
\fC#include 'header\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBM\fP   100"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBpile_init\fP (int numPile)"
.br
.ti -1c
.RI "void \fBpile_empiler\fP (\fBt_coord\fP coord, int numPile)"
.br
.ti -1c
.RI "void \fBpile_depiler\fP (\fBt_coord\fP *coord, int numPile)"
.br
.ti -1c
.RI "int \fBpile_sommet\fP (\fBt_coord\fP *coord, int numPile)"
.br
.ti -1c
.RI "int \fBpilevide\fP (int numPile)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Projet informatique S3 Deplacement du personnage et colisions sur le parois\&. 

\fBAuteur:\fP
.RS 4
TOULMONDE Joris 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.2 
.RE
.PP
\fBDate:\fP
.RS 4
22 Octobre 2014 
.RE
.PP

.PP
Définition dans le fichier \fBpile\&.c\fP\&.
.SH "Documentation des macros"
.PP 
.SS "#define M   100"

.PP
Définition à la ligne 15 du fichier pile\&.c\&.
.SH "Documentation des fonctions"
.PP 
.SS "void pile_depiler (\fBt_coord\fP *coord, intnumPile)"

.PP
Définition à la ligne 35 du fichier pile\&.c\&.
.SS "void pile_empiler (\fBt_coord\fPcoord, intnumPile)"

.PP
Définition à la ligne 26 du fichier pile\&.c\&.
.SS "void pile_init (intnumPile)"

.PP
Définition à la ligne 22 du fichier pile\&.c\&.
.SS "int pile_sommet (\fBt_coord\fP *coord, intnumPile)"

.PP
Définition à la ligne 43 du fichier pile\&.c\&.
.SS "int pilevide (intnumPile)"

.PP
Définition à la ligne 52 du fichier pile\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Le jeu 4 à partir du code source\&.
