.TH "t_character" 3 "Jeudi Janvier 15 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_character \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "char \fBname\fP [\fBMaxString\fP]"
.br
.ti -1c
.RI "\fBt_coord\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBt_orientation\fP \fBorientation\fP"
.br
.ti -1c
.RI "\fBt_status\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBt_stats\fP \fBstats\fP"
.br
.ti -1c
.RI "\fBt_skill_list\fP \fBskill\fP"
.br
.ti -1c
.RI "\fBt_camp\fP \fBcamp\fP"
.br
.ti -1c
.RI "int \fBnb_action_tour\fP"
.br
.ti -1c
.RI "\fBt_character_type\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBt_classe\fP \fBclasse\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 85 du fichier header\&.h\&.
.SH "Documentation des champs"
.PP 
.SS "\fBt_camp\fP camp"

.PP
Définition à la ligne 85 du fichier header\&.h\&.
.SS "\fBt_classe\fP classe"

.PP
Définition à la ligne 85 du fichier header\&.h\&.
.SS "char name[\fBMaxString\fP]"

.PP
Définition à la ligne 85 du fichier header\&.h\&.
.SS "int nb_action_tour"

.PP
Définition à la ligne 85 du fichier header\&.h\&.
.SS "\fBt_orientation\fP orientation"

.PP
Définition à la ligne 85 du fichier header\&.h\&.
.SS "\fBt_coord\fP position"

.PP
Définition à la ligne 85 du fichier header\&.h\&.
.SS "\fBt_skill_list\fP skill"

.PP
Définition à la ligne 85 du fichier header\&.h\&.
.SS "\fBt_stats\fP stats"

.PP
Définition à la ligne 85 du fichier header\&.h\&.
.SS "\fBt_status\fP status"

.PP
Définition à la ligne 85 du fichier header\&.h\&.
.SS "\fBt_character_type\fP type"

.PP
Définition à la ligne 85 du fichier header\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Le jeu 4 à partir du code source\&.
