.TH "t_coord" 3 "Mardi Janvier 13 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_coord \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBX\fP"
.br
.ti -1c
.RI "int \fBY\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 81 du fichier header\&.h\&.
.SH "Documentation des champs"
.PP 
.SS "int X"

.PP
Définition à la ligne 81 du fichier header\&.h\&.
.SS "int Y"

.PP
Définition à la ligne 81 du fichier header\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Le jeu 4 à partir du code source\&.
