.TH "t_coord" 3 "Tue Jan 6 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_coord \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBX\fP"
.br
.ti -1c
.RI "int \fBY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file header\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int X"

.PP
Definition at line 38 of file header\&.h\&.
.SS "int Y"

.PP
Definition at line 38 of file header\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Le jeu 4 from the source code\&.
