.TH "t_player" 3 "Vendredi 16 Janvier 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_player \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBalive\fP"
.br
.ti -1c
.RI "char \fBname\fP [\fBMaxString\fP]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 87 du fichier header\&.h\&.
.SH "Documentation des champs"
.PP 
.SS "int alive"

.PP
Définition à la ligne 87 du fichier header\&.h\&.
.SS "char name[\fBMaxString\fP]"

.PP
Définition à la ligne 87 du fichier header\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Le jeu 4 à partir du code source\&.
