.TH "t_richesses" 3 "Mercredi Janvier 7 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_richesses \- 
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "\fBt_argent\fP \fBargent\fP"
.br
.ti -1c
.RI "int \fBjoyaux\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 11 du fichier Minimale_sans_Plateau_Global\&.c\&.
.SH "Documentation des champs"
.PP 
.SS "\fBt_argent\fP argent"

.PP
Définition à la ligne 11 du fichier Minimale_sans_Plateau_Global\&.c\&.
.SS "int joyaux"

.PP
Définition à la ligne 11 du fichier Minimale_sans_Plateau_Global\&.c\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Le jeu 4 à partir du code source\&.
