.TH "t_skill_list" 3 "Tue Jan 6 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_skill_list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_skill\fP \fBa\fP"
.br
.ti -1c
.RI "\fBt_skill\fP \fBb\fP"
.br
.ti -1c
.RI "\fBt_skill\fP \fBc\fP"
.br
.ti -1c
.RI "\fBt_skill\fP \fBd\fP"
.br
.ti -1c
.RI "\fBt_skill\fP \fBe\fP"
.br
.ti -1c
.RI "\fBt_skill\fP \fBwait\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file header\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBt_skill\fP a"

.PP
Definition at line 40 of file header\&.h\&.
.SS "\fBt_skill\fP b"

.PP
Definition at line 40 of file header\&.h\&.
.SS "\fBt_skill\fP c"

.PP
Definition at line 40 of file header\&.h\&.
.SS "\fBt_skill\fP d"

.PP
Definition at line 40 of file header\&.h\&.
.SS "\fBt_skill\fP e"

.PP
Definition at line 40 of file header\&.h\&.
.SS "\fBt_skill\fP wait"

.PP
Definition at line 40 of file header\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Le jeu 4 from the source code\&.
