.TH "t_skill" 3 "Mardi Janvier 6 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_skill \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "char \fBname\fP [\fBMaxString\fP]"
.br
.ti -1c
.RI "int \fBrange\fP"
.br
.ti -1c
.RI "\fBt_skilltype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBdamage_coeff\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 39 du fichier header\&.h\&.
.SH "Documentation des champs"
.PP 
.SS "int damage_coeff"

.PP
Définition à la ligne 39 du fichier header\&.h\&.
.SS "char name[\fBMaxString\fP]"

.PP
Définition à la ligne 39 du fichier header\&.h\&.
.SS "int range"

.PP
Définition à la ligne 39 du fichier header\&.h\&.
.SS "\fBt_skilltype\fP type"

.PP
Définition à la ligne 39 du fichier header\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Le jeu 4 à partir du code source\&.
