.TH "t_skill" 3 "Tue Jan 6 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_skill \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [\fBMaxString\fP]"
.br
.ti -1c
.RI "int \fBrange\fP"
.br
.ti -1c
.RI "\fBt_skilltype\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBdamage_coeff\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file header\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int damage_coeff"

.PP
Definition at line 39 of file header\&.h\&.
.SS "char name[\fBMaxString\fP]"

.PP
Definition at line 39 of file header\&.h\&.
.SS "int range"

.PP
Definition at line 39 of file header\&.h\&.
.SS "\fBt_skilltype\fP type"

.PP
Definition at line 39 of file header\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Le jeu 4 from the source code\&.
