.TH "t_status" 3 "Jeudi Janvier 15 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_status \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBHP\fP"
.br
.ti -1c
.RI "int \fBMax_HP\fP"
.br
.ti -1c
.RI "int \fBMP\fP"
.br
.ti -1c
.RI "int \fBMax_MP\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 79 du fichier header\&.h\&.
.SH "Documentation des champs"
.PP 
.SS "int HP"

.PP
Définition à la ligne 79 du fichier header\&.h\&.
.SS "int Max_HP"

.PP
Définition à la ligne 79 du fichier header\&.h\&.
.SS "int Max_MP"

.PP
Définition à la ligne 79 du fichier header\&.h\&.
.SS "int MP"

.PP
Définition à la ligne 79 du fichier header\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Le jeu 4 à partir du code source\&.
