.TH "t_status" 3 "Tue Jan 6 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_status \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBHP\fP"
.br
.ti -1c
.RI "int \fBMax_HP\fP"
.br
.ti -1c
.RI "int \fBMP\fP"
.br
.ti -1c
.RI "int \fBMax_MP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file header\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int HP"

.PP
Definition at line 36 of file header\&.h\&.
.SS "int Max_HP"

.PP
Definition at line 36 of file header\&.h\&.
.SS "int Max_MP"

.PP
Definition at line 36 of file header\&.h\&.
.SS "int MP"

.PP
Definition at line 36 of file header\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Le jeu 4 from the source code\&.
