.TH "t_stats" 3 "Tue Jan 6 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_stats \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBATK\fP"
.br
.ti -1c
.RI "int \fBMATK\fP"
.br
.ti -1c
.RI "int \fBDEF\fP"
.br
.ti -1c
.RI "int \fBMDEF\fP"
.br
.ti -1c
.RI "int \fBMVT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file header\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int ATK"

.PP
Definition at line 37 of file header\&.h\&.
.SS "int DEF"

.PP
Definition at line 37 of file header\&.h\&.
.SS "int MATK"

.PP
Definition at line 37 of file header\&.h\&.
.SS "int MDEF"

.PP
Definition at line 37 of file header\&.h\&.
.SS "int MVT"

.PP
Definition at line 37 of file header\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Le jeu 4 from the source code\&.
