.TH "t_stats" 3 "Mardi Janvier 6 2015" "Version v1.1 Ncurses" "Le jeu 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_stats \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBATK\fP"
.br
.ti -1c
.RI "int \fBMATK\fP"
.br
.ti -1c
.RI "int \fBDEF\fP"
.br
.ti -1c
.RI "int \fBMDEF\fP"
.br
.ti -1c
.RI "int \fBMVT\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 37 du fichier header\&.h\&.
.SH "Documentation des champs"
.PP 
.SS "int ATK"

.PP
Définition à la ligne 37 du fichier header\&.h\&.
.SS "int DEF"

.PP
Définition à la ligne 37 du fichier header\&.h\&.
.SS "int MATK"

.PP
Définition à la ligne 37 du fichier header\&.h\&.
.SS "int MDEF"

.PP
Définition à la ligne 37 du fichier header\&.h\&.
.SS "int MVT"

.PP
Définition à la ligne 37 du fichier header\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Le jeu 4 à partir du code source\&.
